### ISSUE TITLE
dropped content

### ISSUE THREAD

**Issue by ErichBSchulz** [seanmadsen/webpage2md#2]
When using the tool on this page:

https://wiki.civicrm.org/confluence/display/CRMDOC/Create+a+Module+Extension#CreateaModuleExtension-Addcustomfields(CiviCRMv4.4+)

it dropped all the script blocks ie:

![these](http://www.clipular.com/c/6278475222876160.png?k=l7UYcOf8o96kPgvGfZ8VtCPa4Qs)

As it was I decided to reduce these and instead extract out the command to run as it was a bit overwelming and distracted from the main instructions

**Comment by ErichBSchulz** [comment]
the raw output I generated is [here](https://raw.githubusercontent.com/ErichBSchulz/civicrm-dev-docs/c801651a1b8ac3949e91bb6fbdfeaee8fc4475ac/docs/extensions/createamoduleextension.md)

**Comment by seancolsen** [comment]
Verified. 

Thanks for reporting! This seems like a pretty major issue. Will get on it.

**Comment by seancolsen** [comment]
I think this commit should fix this issue fully for 98% of cases. 

The remaining 2% are cases are where the code block contains the string `\n`. In this case, the content still comes through, but with a newline there in the markdown (instead of the string `\n`) which messes up the display of the markdown. 

Despite this case which is not handled perfectly, I'm going to close this issue because the work-around is so easy (reformatting the markdown to replace the newline with `\n`). Going forward, this behavior will be a known limitation.
